formation_app_devis:
    resource: "@FormationAppBundle/Controller/DevisController.php"
    type:     annotation

formation_app_contact:
    resource: "@FormationAppBundle/Controller/ContactController.php"
    type:     annotation

formation_app_subscriber:
    resource: "@FormationAppBundle/Controller/SubscriberController.php"
    type:     annotation

formation_app_inscription:
    resource: "@FormationAppBundle/Controller/InscriptionController.php"
    type:     annotation

formation_app_course:
    resource: "@FormationAppBundle/Controller/CourseController.php"
    type:     annotation

formation_app_categorie:
    resource: "@FormationAppBundle/Controller/CategorieController.php"
    type:     annotation

formation_app:
    resource: "@FormationAppBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


